/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminDashboardTestimonialsRouteImport } from './routes/admin.dashboard.testimonials'
import { Route as AdminDashboardScheduleRouteImport } from './routes/admin.dashboard.schedule'
import { Route as AdminDashboardMembershipsRouteImport } from './routes/admin.dashboard.memberships'
import { Route as AdminDashboardMembersRouteImport } from './routes/admin.dashboard.members'
import { Route as AdminDashboardFreeTrialsRouteImport } from './routes/admin.dashboard.free-trials'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardTestimonialsRoute =
  AdminDashboardTestimonialsRouteImport.update({
    id: '/testimonials',
    path: '/testimonials',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardScheduleRoute = AdminDashboardScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardMembershipsRoute =
  AdminDashboardMembershipsRouteImport.update({
    id: '/memberships',
    path: '/memberships',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardMembersRoute = AdminDashboardMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardFreeTrialsRoute =
  AdminDashboardFreeTrialsRouteImport.update({
    id: '/free-trials',
    path: '/free-trials',
    getParentRoute: () => AdminDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/admin/dashboard/free-trials': typeof AdminDashboardFreeTrialsRoute
  '/admin/dashboard/members': typeof AdminDashboardMembersRoute
  '/admin/dashboard/memberships': typeof AdminDashboardMembershipsRoute
  '/admin/dashboard/schedule': typeof AdminDashboardScheduleRoute
  '/admin/dashboard/testimonials': typeof AdminDashboardTestimonialsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/admin/dashboard/free-trials': typeof AdminDashboardFreeTrialsRoute
  '/admin/dashboard/members': typeof AdminDashboardMembersRoute
  '/admin/dashboard/memberships': typeof AdminDashboardMembershipsRoute
  '/admin/dashboard/schedule': typeof AdminDashboardScheduleRoute
  '/admin/dashboard/testimonials': typeof AdminDashboardTestimonialsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/admin/dashboard/free-trials': typeof AdminDashboardFreeTrialsRoute
  '/admin/dashboard/members': typeof AdminDashboardMembersRoute
  '/admin/dashboard/memberships': typeof AdminDashboardMembershipsRoute
  '/admin/dashboard/schedule': typeof AdminDashboardScheduleRoute
  '/admin/dashboard/testimonials': typeof AdminDashboardTestimonialsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/privacy-policy'
    | '/refund-policy'
    | '/terms-and-conditions'
    | '/admin/dashboard'
    | '/admin/dashboard/free-trials'
    | '/admin/dashboard/members'
    | '/admin/dashboard/memberships'
    | '/admin/dashboard/schedule'
    | '/admin/dashboard/testimonials'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/privacy-policy'
    | '/refund-policy'
    | '/terms-and-conditions'
    | '/admin/dashboard'
    | '/admin/dashboard/free-trials'
    | '/admin/dashboard/members'
    | '/admin/dashboard/memberships'
    | '/admin/dashboard/schedule'
    | '/admin/dashboard/testimonials'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/privacy-policy'
    | '/refund-policy'
    | '/terms-and-conditions'
    | '/admin/dashboard'
    | '/admin/dashboard/free-trials'
    | '/admin/dashboard/members'
    | '/admin/dashboard/memberships'
    | '/admin/dashboard/schedule'
    | '/admin/dashboard/testimonials'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard/testimonials': {
      id: '/admin/dashboard/testimonials'
      path: '/testimonials'
      fullPath: '/admin/dashboard/testimonials'
      preLoaderRoute: typeof AdminDashboardTestimonialsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/schedule': {
      id: '/admin/dashboard/schedule'
      path: '/schedule'
      fullPath: '/admin/dashboard/schedule'
      preLoaderRoute: typeof AdminDashboardScheduleRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/memberships': {
      id: '/admin/dashboard/memberships'
      path: '/memberships'
      fullPath: '/admin/dashboard/memberships'
      preLoaderRoute: typeof AdminDashboardMembershipsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/members': {
      id: '/admin/dashboard/members'
      path: '/members'
      fullPath: '/admin/dashboard/members'
      preLoaderRoute: typeof AdminDashboardMembersRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/free-trials': {
      id: '/admin/dashboard/free-trials'
      path: '/free-trials'
      fullPath: '/admin/dashboard/free-trials'
      preLoaderRoute: typeof AdminDashboardFreeTrialsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
  }
}

interface AdminDashboardRouteChildren {
  AdminDashboardFreeTrialsRoute: typeof AdminDashboardFreeTrialsRoute
  AdminDashboardMembersRoute: typeof AdminDashboardMembersRoute
  AdminDashboardMembershipsRoute: typeof AdminDashboardMembershipsRoute
  AdminDashboardScheduleRoute: typeof AdminDashboardScheduleRoute
  AdminDashboardTestimonialsRoute: typeof AdminDashboardTestimonialsRoute
}

const AdminDashboardRouteChildren: AdminDashboardRouteChildren = {
  AdminDashboardFreeTrialsRoute: AdminDashboardFreeTrialsRoute,
  AdminDashboardMembersRoute: AdminDashboardMembersRoute,
  AdminDashboardMembershipsRoute: AdminDashboardMembershipsRoute,
  AdminDashboardScheduleRoute: AdminDashboardScheduleRoute,
  AdminDashboardTestimonialsRoute: AdminDashboardTestimonialsRoute,
}

const AdminDashboardRouteWithChildren = AdminDashboardRoute._addFileChildren(
  AdminDashboardRouteChildren,
)

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
